proxy:
  ip: 39.108.82.36
  port: 8888
  passwd: PrrukLRXJfwWbMsn
  mapping:
    - facadePort: 8123
      realPort: 8000
      realIp: 127.0.0.1
    - facadePort: 10180
      realPort: 10080
      realIp: 127.0.0.1
    - facadePort: 10122
      realPort: 10022
      realIp: 127.0.0.1
